# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pygecko/proto/nav_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pygecko.proto import standard_msgs_pb2 as pygecko_dot_proto_dot_standard__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pygecko/proto/nav_msgs.proto',
  package='nav_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cpygecko/proto/nav_msgs.proto\x12\x08nav_msgs\x1a!pygecko/proto/standard_msgs.proto\"r\n\x04Pose\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\'\n\x08position\x18\x02 \x01(\x0b\x32\x15.standard_msgs.Vector\x12.\n\x0borientation\x18\x03 \x01(\x0b\x32\x19.standard_msgs.Quaternion\"r\n\x08Odometry\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x1c\n\x04pose\x18\x02 \x01(\x0b\x32\x0e.nav_msgs.Pose\x12#\n\x05twist\x18\x03 \x01(\x0b\x32\x14.standard_msgs.Twist\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\t\"\x83\x01\n\rOccupancyGrid\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x12\n\nresolution\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12\x1e\n\x06origin\x18\x05 \x01(\x0b\x32\x0e.nav_msgs.Pose\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"8\n\x04Path\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x1d\n\x05poses\x18\x02 \x03(\x0b\x32\x0e.nav_msgs.Poseb\x06proto3')
  ,
  dependencies=[pygecko_dot_proto_dot_standard__msgs__pb2.DESCRIPTOR,])




_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='nav_msgs.Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nav_msgs.Pose.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='nav_msgs.Pose.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='nav_msgs.Pose.orientation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=191,
)


_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='nav_msgs.Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nav_msgs.Odometry.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='nav_msgs.Odometry.pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='twist', full_name='nav_msgs.Odometry.twist', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='nav_msgs.Odometry.frame_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=307,
)


_OCCUPANCYGRID = _descriptor.Descriptor(
  name='OccupancyGrid',
  full_name='nav_msgs.OccupancyGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nav_msgs.OccupancyGrid.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='nav_msgs.OccupancyGrid.resolution', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='nav_msgs.OccupancyGrid.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='nav_msgs.OccupancyGrid.height', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin', full_name='nav_msgs.OccupancyGrid.origin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='nav_msgs.OccupancyGrid.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=441,
)


_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='nav_msgs.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nav_msgs.Path.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poses', full_name='nav_msgs.Path.poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=499,
)

_POSE.fields_by_name['position'].message_type = pygecko_dot_proto_dot_standard__msgs__pb2._VECTOR
_POSE.fields_by_name['orientation'].message_type = pygecko_dot_proto_dot_standard__msgs__pb2._QUATERNION
_ODOMETRY.fields_by_name['pose'].message_type = _POSE
_ODOMETRY.fields_by_name['twist'].message_type = pygecko_dot_proto_dot_standard__msgs__pb2._TWIST
_OCCUPANCYGRID.fields_by_name['origin'].message_type = _POSE
_PATH.fields_by_name['poses'].message_type = _POSE
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY
DESCRIPTOR.message_types_by_name['OccupancyGrid'] = _OCCUPANCYGRID
DESCRIPTOR.message_types_by_name['Path'] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'pygecko.proto.nav_msgs_pb2'
  # @@protoc_insertion_point(class_scope:nav_msgs.Pose)
  })
_sym_db.RegisterMessage(Pose)

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), {
  'DESCRIPTOR' : _ODOMETRY,
  '__module__' : 'pygecko.proto.nav_msgs_pb2'
  # @@protoc_insertion_point(class_scope:nav_msgs.Odometry)
  })
_sym_db.RegisterMessage(Odometry)

OccupancyGrid = _reflection.GeneratedProtocolMessageType('OccupancyGrid', (_message.Message,), {
  'DESCRIPTOR' : _OCCUPANCYGRID,
  '__module__' : 'pygecko.proto.nav_msgs_pb2'
  # @@protoc_insertion_point(class_scope:nav_msgs.OccupancyGrid)
  })
_sym_db.RegisterMessage(OccupancyGrid)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'pygecko.proto.nav_msgs_pb2'
  # @@protoc_insertion_point(class_scope:nav_msgs.Path)
  })
_sym_db.RegisterMessage(Path)


# @@protoc_insertion_point(module_scope)
