
# capnp compile -o c++ vec.capnp
# this command generates:
#     vec.capnp.h/c++

# this was generated by the command above the first time i ran it
@0xb656ea4cd4b75887;

struct Vector {
    id @0 :UInt8;
    x  @1 :Float64;
    y  @2 :Float64;
    z  @3 :Float64;
}

# struct IMU {
#     accel      @0 :Vector;
#     gyro       @1 :Vector;
#     mag        @2 :Vector;
#     timestamp  @3 :Float64;
# }
